name: Publish Docker image
on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: spirtis/test-actions

      - name: Build and push Docker tag image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        if: startsWith(github.ref, 'refs/tags')
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get current time
        if: startsWith(github.ref, 'refs/tags') != true
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH.MM.SS
      - name: Build and push Docker main image
        if: startsWith(github.ref, 'refs/tags') != true
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.current-time.outputs.formattedTime }}
          labels: ${{ steps.meta.outputs.labels }}